import { describe, expect, it } from "vitest";

import { chooseArtifactKindFromText, getActionToolForArtifactKind } from "../src/shared/agent";
import {
  buildDesignSourceContext,
  buildGeneratedArtifactReview,
  createDesignProjectFromArtifact,
  defaultArtifactContent,
  getActiveArtifactVersion,
  getArtifactExportTargets,
  isAiDesignProject,
  sanitizeArtifacts,
  type Artifact
} from "../src/shared/artifacts";

describe("artifact models", () => {
  it("routes email text to the expected artifact kind", () => {
    expect(chooseArtifactKindFromText("Please make a slide deck for the meeting")).toBe("slide_deck");
    expect(chooseArtifactKindFromText("Can you design a landing page mockup?")).toBe("website_design");
    expect(chooseArtifactKindFromText("Write a report from these notes")).toBe("document");
  });

  it("maps artifact kinds to agent tools", () => {
    expect(getActionToolForArtifactKind("document")).toBe("document");
    expect(getActionToolForArtifactKind("slide_deck")).toBe("slide_deck");
    expect(getActionToolForArtifactKind("website_design")).toBe("website_design");
  });

  it("keeps active versions and preserves website markup", () => {
    const artifact: Artifact = {
      id: "artifact",
      kind: "website_design",
      title: "Landing page",
      summary: "Website",
      source: { provider: "manual", label: "Manual" },
      visibility: "user_project",
      pinned: false,
      activeVersionId: "version-2",
      versions: [
        {
          id: "version-1",
          createdAt: 1,
          prompt: "first",
          summary: "first",
          content: defaultArtifactContent("website_design")
        },
        {
          id: "version-2",
          createdAt: 2,
          prompt: "second",
          summary: "second",
          content: {
            kind: "website_design",
            html: "<main>\n  <h1>Hello</h1>\n</main>",
            css: "main {\n  color: red;\n}",
            sections: [{ id: "hero", name: "Hero", summary: "Opening" }]
          }
        }
      ],
      createdAt: 1,
      updatedAt: 2
    };

    const [sanitized] = sanitizeArtifacts([artifact]);
    const version = getActiveArtifactVersion(sanitized);
    expect(version.id).toBe("version-2");
    expect(version.content.kind).toBe("website_design");
    if (version.content.kind === "website_design") {
      expect(version.content.html).toContain("\n  <h1>Hello</h1>");
      expect(version.content.css).toContain("\n  color: red;");
    }
  });

  it("defaults Gmail artifacts into AI generated projects", () => {
    const [gmailArtifact, manualArtifact] = sanitizeArtifacts([
      {
        kind: "document",
        title: "Email work",
        source: { provider: "gmail", label: "Gmail request" },
        activeVersionId: "version-1",
        versions: [
          {
            id: "version-1",
            createdAt: 1,
            prompt: "email",
            summary: "email",
            content: defaultArtifactContent("document")
          }
        ]
      },
      {
        kind: "website_design",
        title: "Manual work",
        source: { provider: "manual", label: "Prompt" },
        activeVersionId: "version-2",
        versions: [
          {
            id: "version-2",
            createdAt: 1,
            prompt: "manual",
            summary: "manual",
            content: defaultArtifactContent("website_design")
          }
        ]
      }
    ]);

    expect(gmailArtifact.visibility).toBe("ai_generated");
    expect(manualArtifact.visibility).toBe("user_project");
  });

  it("keeps action-plan-backed manual artifacts visible in AI projects", () => {
    const [manualArtifact] = sanitizeArtifacts([
      {
        kind: "document",
        title: "Manual prompt output",
        source: { provider: "manual", label: "Prompt from Design chat" },
        activeVersionId: "version-1",
        versions: [
          {
            id: "version-1",
            createdAt: 1,
            prompt: "Generate a project brief",
            summary: "Generated by the agent",
            content: defaultArtifactContent("document")
          }
        ]
      }
    ]);

    const humanProject = createDesignProjectFromArtifact(manualArtifact);
    const aiProject = createDesignProjectFromArtifact(manualArtifact, false, true);

    expect(humanProject.visibility).toBe("user_project");
    expect(isAiDesignProject(humanProject)).toBe(false);
    expect(isAiDesignProject(aiProject)).toBe(true);
  });

  it("builds source context for Gmail artifacts", () => {
    const [artifact] = sanitizeArtifacts([
      {
        kind: "document",
        title: "Teacher follow-up",
        source: {
          provider: "gmail",
          label: "Teacher - Resume slides",
          subject: "Please prepare resume slides",
          from: "Teacher",
          fromEmail: "teacher@example.com",
          messageId: "msg-1",
          threadId: "thread-1",
          url: "https://mail.google.com/mail/u/0/#inbox/msg-1"
        },
        activeVersionId: "version-1",
        versions: [
          {
            id: "version-1",
            createdAt: 1,
            prompt: "Turn the email into a polished document.",
            summary: "Prepared a structured response.",
            content: {
              kind: "document",
              markdown:
                "# Teacher follow-up\n\nThis document explains the requested deliverable, lists the next steps, and gives a clear structure for review before sending."
            }
          }
        ]
      }
    ]);

    const context = buildDesignSourceContext(artifact);
    expect(context.heading).toBe("Original email");
    expect(context.description).toBe("Please prepare resume slides");
    expect(context.meta).toContain("From Teacher");
    expect(context.requirements.join(" ")).toContain("Turn the email into a polished document.");

    const review = buildGeneratedArtifactReview(artifact);
    expect(review.kindLabel).toBe("Document");
    expect(review.approvalState).toBe("needs_review");
    expect(review.exportTargets).toEqual([
      expect.objectContaining({ id: "docx", label: "Export DOCX", action: "export" })
    ]);
  });

  it("marks website artifacts as exportable to Coding", () => {
    const [artifact] = sanitizeArtifacts([
      {
        kind: "website_design",
        title: "Marketing page",
        source: { provider: "manual", label: "Landing page prompt" },
        activeVersionId: "version-1",
        versions: [
          {
            id: "version-1",
            createdAt: 1,
            prompt: "Design a focused marketing page.",
            summary: "Website draft",
            content: {
              kind: "website_design",
              html:
                "<main><section><h1>Autopilot</h1><p>Turn scattered work requests into reviewed drafts, designs, and code changes.</p><button>Start review</button></section><section><h2>Workflow</h2><p>Read the source, prepare the output, and keep final sharing behind approval.</p></section></main>",
              css: "main { color: #123c2b; } section { padding: 48px; } button { border-radius: 999px; }",
              sections: [
                { id: "hero", name: "Hero", summary: "Main promise" },
                { id: "workflow", name: "Workflow", summary: "Reviewable work loop" }
              ]
            }
          }
        ]
      }
    ]);

    expect(getArtifactExportTargets(artifact).map((target) => target.id)).toEqual(["html_css", "coding_project"]);
    const review = buildGeneratedArtifactReview(artifact);
    expect(review.exportReady).toBe(true);
    expect(review.exportTargets).toEqual([
      expect.objectContaining({ id: "html_css", available: true }),
      expect.objectContaining({ id: "coding_project", action: "to_coding", available: true })
    ]);
  });
});
