import type { EmailMessageSummary } from "./email.js";
import type { CodingSnapshot } from "./coding.js";

export type ArtifactKind = "document" | "slide_deck" | "website_design";
export type ArtifactVisibility = "user_project" | "ai_generated" | "archived";

export type ArtifactSource = {
  provider: "gmail" | "manual";
  label: string;
  messageId?: string;
  threadId?: string;
  url?: string;
  from?: string;
  fromEmail?: string;
  subject?: string;
};

export type DocumentArtifactContent = {
  kind: "document";
  markdown: string;
};

export type SlideArtifactSlide = {
  id: string;
  title: string;
  bullets: string[];
  speakerNotes?: string;
};

export type SlideDeckArtifactContent = {
  kind: "slide_deck";
  slides: SlideArtifactSlide[];
};

export type WebsiteDesignSection = {
  id: string;
  name: string;
  summary: string;
};

export type WebsiteDesignArtifactContent = {
  kind: "website_design";
  html: string;
  css: string;
  sections: WebsiteDesignSection[];
};

export type ArtifactContent = DocumentArtifactContent | SlideDeckArtifactContent | WebsiteDesignArtifactContent;

export type ArtifactVersion = {
  id: string;
  createdAt: number;
  prompt: string;
  summary: string;
  content: ArtifactContent;
};

export type Artifact = {
  id: string;
  kind: ArtifactKind;
  title: string;
  summary: string;
  source: ArtifactSource;
  visibility: ArtifactVisibility;
  pinned: boolean;
  exportedProjectPath?: string;
  versions: ArtifactVersion[];
  activeVersionId: string;
  createdAt: number;
  updatedAt: number;
};

export type DesignProject = {
  id: string;
  artifactId: string;
  title: string;
  summary: string;
  kind: ArtifactKind;
  visibility: ArtifactVisibility;
  pinned: boolean;
  sourceLabel: string;
  updatedAt: number;
  needsReview: boolean;
  exportedProjectPath?: string;
};

export type ArtifactCreateInput = {
  kind: ArtifactKind;
  title: string;
  summary?: string;
  prompt?: string;
  source?: Partial<ArtifactSource>;
  visibility?: ArtifactVisibility;
  pinned?: boolean;
  content: ArtifactContent;
};

export type ArtifactUpdateInput = {
  artifactId: string;
  prompt: string;
  summary?: string;
  content: ArtifactContent;
};

export type ArtifactExportResult =
  | {
      success: true;
      artifactId: string;
      kind: ArtifactKind;
      path: string;
      exportedAt: number;
    }
  | {
      success: false;
      artifactId: string;
      kind?: ArtifactKind;
      reason: string;
    };

export type ArtifactExportToCodingResult =
  | {
      success: true;
      artifactId: string;
      kind: ArtifactKind;
      path: string;
      projectRootPath: string;
      exportedAt: number;
      codingSnapshot: CodingSnapshot;
    }
  | {
      success: false;
      artifactId: string;
      kind?: ArtifactKind;
      reason: string;
    };

export function createArtifactSourceFromEmail(message: EmailMessageSummary): ArtifactSource {
  return {
    provider: "gmail",
    label: `${message.from} - ${message.subject}`.slice(0, 160),
    messageId: message.id,
    threadId: message.threadId,
    url: message.url,
    from: message.from,
    fromEmail: message.fromEmail,
    subject: message.subject
  };
}

export function sanitizeArtifactKind(value: unknown): ArtifactKind {
  return value === "slide_deck" || value === "website_design" ? value : "document";
}

export function sanitizeArtifacts(value: unknown): Artifact[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.flatMap((item) => {
    const artifact = sanitizeArtifact(item);
    return artifact ? [artifact] : [];
  });
}

export function sanitizeArtifact(value: unknown): Artifact | null {
  if (!value || typeof value !== "object") {
    return null;
  }

  const candidate = value as Partial<Artifact>;
  const kind = sanitizeArtifactKind(candidate.kind);
  const versions = Array.isArray(candidate.versions)
    ? candidate.versions.flatMap((version) => {
        const sanitizedVersion = sanitizeArtifactVersion(version, kind);
        return sanitizedVersion ? [sanitizedVersion] : [];
      })
    : [];
  if (versions.length === 0) {
    return null;
  }

  const activeVersionId =
    typeof candidate.activeVersionId === "string" && versions.some((version) => version.id === candidate.activeVersionId)
      ? candidate.activeVersionId
      : versions[versions.length - 1].id;

  return {
    id: cleanString(candidate.id, 160) || makeArtifactId(kind),
    kind,
    title: cleanString(candidate.title, 160) || defaultArtifactTitle(kind),
    summary: cleanString(candidate.summary, 360) || "Generated by Autopilot.",
    source: sanitizeArtifactSource(candidate.source),
    visibility: sanitizeArtifactVisibility(candidate.visibility, candidate.source),
    pinned: Boolean(candidate.pinned),
    exportedProjectPath: cleanString(candidate.exportedProjectPath, 2048) || undefined,
    versions,
    activeVersionId,
    createdAt: cleanTime(candidate.createdAt),
    updatedAt: cleanTime(candidate.updatedAt)
  };
}

export function getActiveArtifactVersion(artifact: Artifact): ArtifactVersion {
  return artifact.versions.find((version) => version.id === artifact.activeVersionId) ?? artifact.versions[artifact.versions.length - 1];
}

export function getArtifactTextPreview(artifact: Artifact): string {
  const version = getActiveArtifactVersion(artifact);
  switch (version.content.kind) {
    case "document":
      return version.content.markdown;
    case "slide_deck":
      return version.content.slides.map((slide) => `${slide.title}\n${slide.bullets.join("\n")}`).join("\n\n");
    case "website_design":
      return `${version.content.sections.map((section) => section.name).join(", ")}\n${version.content.html}`;
  }
}

export function createDesignProjectFromArtifact(artifact: Artifact, needsReview = false): DesignProject {
  return {
    id: `design-project:${artifact.id}`,
    artifactId: artifact.id,
    title: artifact.title,
    summary: artifact.summary,
    kind: artifact.kind,
    visibility: artifact.visibility,
    pinned: artifact.pinned,
    sourceLabel: artifact.source.label,
    updatedAt: artifact.updatedAt,
    needsReview,
    exportedProjectPath: artifact.exportedProjectPath
  };
}

export function defaultArtifactContent(kind: ArtifactKind, title = defaultArtifactTitle(kind)): ArtifactContent {
  switch (kind) {
    case "slide_deck":
      return {
        kind,
        slides: [
          {
            id: makeId("slide"),
            title,
            bullets: ["Autopilot will build this deck from the selected context.", "Ask for a revision to shape the story."],
            speakerNotes: "Generated as a starter deck."
          }
        ]
      };
    case "website_design":
      return {
        kind,
        html: `<main class="artifact-page"><section class="hero"><p>Autopilot</p><h1>${escapeHtml(title)}</h1><span>Generated website design</span></section></main>`,
        css: ".artifact-page{min-height:100vh;padding:64px;font-family:Inter,system-ui,sans-serif;background:#fff8ed;color:#123c2b}.hero{max-width:760px}.hero p{text-transform:uppercase;letter-spacing:.08em;color:#b67349}.hero h1{font-size:64px;line-height:1;margin:0 0 16px}",
        sections: [
          {
            id: makeId("section"),
            name: "Hero",
            summary: "Opening section generated by Autopilot."
          }
        ]
      };
    case "document":
      return {
        kind,
        markdown: `# ${title}\n\nAutopilot will draft this document from the selected context.\n`
      };
  }
}

export function defaultArtifactTitle(kind: ArtifactKind): string {
  switch (kind) {
    case "slide_deck":
      return "Generated slide deck";
    case "website_design":
      return "Generated website design";
    case "document":
      return "Generated document";
  }
}

export function makeArtifactId(kind: ArtifactKind): string {
  return makeId(`artifact-${kind}`);
}

export function makeArtifactVersionId(): string {
  return makeId("version");
}

function sanitizeArtifactVersion(value: unknown, fallbackKind: ArtifactKind): ArtifactVersion | null {
  if (!value || typeof value !== "object") {
    return null;
  }

  const version = value as Partial<ArtifactVersion>;
  const content = sanitizeArtifactContent(version.content, fallbackKind);
  if (!content) {
    return null;
  }

  return {
    id: cleanString(version.id, 160) || makeArtifactVersionId(),
    createdAt: cleanTime(version.createdAt),
    prompt: cleanString(version.prompt, 2000) || "Generated by Autopilot.",
    summary: cleanString(version.summary, 360) || "Autopilot generated this version.",
    content
  };
}

function sanitizeArtifactContent(value: unknown, fallbackKind: ArtifactKind): ArtifactContent | null {
  if (!value || typeof value !== "object") {
    return defaultArtifactContent(fallbackKind);
  }

  const content = value as Partial<ArtifactContent>;
  const kind = sanitizeArtifactKind(content.kind);
  if (kind === "document") {
    const markdown = cleanBlockString((content as Partial<DocumentArtifactContent>).markdown, 50000);
    return {
      kind,
      markdown: markdown || "# Generated document\n\nNo content yet.\n"
    };
  }

  if (kind === "slide_deck") {
    const rawSlides = (content as Partial<SlideDeckArtifactContent>).slides;
    const slides = Array.isArray(rawSlides)
      ? rawSlides.flatMap((slide) => {
          if (!slide || typeof slide !== "object") {
            return [];
          }

          const candidate = slide as Partial<SlideArtifactSlide>;
          const title = cleanString(candidate.title, 180);
          if (!title) {
            return [];
          }

          const bullets = Array.isArray(candidate.bullets)
            ? candidate.bullets.map((bullet) => cleanString(bullet, 220)).filter(Boolean).slice(0, 8)
            : [];

          return [
            {
              id: cleanString(candidate.id, 120) || makeId("slide"),
              title,
              bullets: bullets.length > 0 ? bullets : ["Add supporting detail."],
              speakerNotes: cleanString(candidate.speakerNotes, 1000) || undefined
            }
          ];
        })
      : [];

    return {
      kind,
      slides:
        slides.length > 0
          ? slides.slice(0, 24)
          : [
              {
                id: makeId("slide"),
                title: "Generated slide",
                bullets: ["No content yet."]
              }
            ]
    };
  }

  const website = content as Partial<WebsiteDesignArtifactContent>;
  const sections = Array.isArray(website.sections)
    ? website.sections
        .flatMap((section) => {
          if (!section || typeof section !== "object") {
            return [];
          }

          const candidate = section as Partial<WebsiteDesignSection>;
          const name = cleanString(candidate.name, 120);
          if (!name) {
            return [];
          }

          return [
            {
              id: cleanString(candidate.id, 120) || makeId("section"),
              name,
              summary: cleanString(candidate.summary, 360) || "Generated section."
            }
          ];
        })
        .slice(0, 24)
    : [];

  const fallbackWebsite = defaultArtifactContent("website_design");
  return {
    kind,
    html: cleanBlockString(website.html, 100000) || (fallbackWebsite.kind === "website_design" ? fallbackWebsite.html : ""),
    css: cleanBlockString(website.css, 100000) || (fallbackWebsite.kind === "website_design" ? fallbackWebsite.css : ""),
    sections
  };
}

function sanitizeArtifactSource(value: unknown): ArtifactSource {
  if (!value || typeof value !== "object") {
    return {
      provider: "manual",
      label: "Manual prompt"
    };
  }

  const source = value as Partial<ArtifactSource>;
  return {
    provider: source.provider === "gmail" ? "gmail" : "manual",
    label: cleanString(source.label, 180) || "Manual prompt",
    messageId: cleanString(source.messageId, 220) || undefined,
    threadId: cleanString(source.threadId, 220) || undefined,
    url: cleanString(source.url, 2048) || undefined,
    from: cleanString(source.from, 180) || undefined,
    fromEmail: cleanString(source.fromEmail, 220) || undefined,
    subject: cleanString(source.subject, 260) || undefined
  };
}

function sanitizeArtifactVisibility(value: unknown, source: unknown): ArtifactVisibility {
  if (value === "user_project" || value === "ai_generated" || value === "archived") {
    return value;
  }

  if (source && typeof source === "object" && (source as Partial<ArtifactSource>).provider === "gmail") {
    return "ai_generated";
  }

  return "user_project";
}

function cleanString(value: unknown, maxLength: number): string {
  return typeof value === "string" ? value.replace(/\s+/g, " ").trim().slice(0, maxLength) : "";
}

function cleanBlockString(value: unknown, maxLength: number): string {
  return typeof value === "string" ? value.replace(/\r/g, "").trim().slice(0, maxLength) : "";
}

function cleanTime(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : Date.now();
}

function makeId(prefix: string): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `${prefix}:${crypto.randomUUID()}`;
  }

  return `${prefix}:${Date.now().toString(36)}:${Math.random().toString(36).slice(2, 10)}`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => {
    switch (character) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      case "'":
        return "&#39;";
      default:
        return character;
    }
  });
}
