import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import JSZip from "jszip";

import {
  defaultArtifactContent,
  defaultArtifactTitle,
  getActiveArtifactVersion,
  sanitizeArtifact,
  sanitizeArtifacts,
  type Artifact,
  type ArtifactCreateInput,
  type ArtifactExportResult,
  type ArtifactExportToCodingResult,
  type ArtifactUpdateInput,
  type SlideArtifactSlide
} from "../shared/artifacts.js";

const ARTIFACTS_FILE = "artifacts.json";

type ArtifactFile = {
  version: 1;
  artifacts: Artifact[];
};

export class ArtifactStore {
  private artifacts: Artifact[] | null = null;

  constructor(
    private readonly dataRoot: string | (() => string),
    private readonly exportRoot: string | (() => string)
  ) {}

  async listArtifacts(): Promise<Artifact[]> {
    return structuredClone(await this.ensureLoaded());
  }

  async createArtifact(input: ArtifactCreateInput): Promise<Artifact> {
    const now = Date.now();
    const kind = input.kind;
    const versionId = makeId("version");
    const content = input.content?.kind === kind ? input.content : defaultArtifactContent(kind);
    const artifact = sanitizeArtifact({
      id: makeId(`artifact-${kind}`),
      kind,
      title: input.title || defaultArtifactTitle(kind),
      summary: input.summary || "Generated by Autopilot.",
      emailDraftMarkdown: input.emailDraftMarkdown,
      source: input.source ?? { provider: "manual", label: "Manual prompt" },
      visibility: input.visibility,
      pinned: input.pinned,
      activeVersionId: versionId,
      versions: [
        {
          id: versionId,
          createdAt: now,
          prompt: input.prompt || "Generated by Autopilot.",
          summary: input.summary || "Initial version.",
          content
        }
      ],
      createdAt: now,
      updatedAt: now
    });

    if (!artifact) {
      throw new Error("Unable to create artifact.");
    }

    const artifacts = await this.ensureLoaded();
    this.artifacts = [artifact, ...artifacts];
    await this.save();
    return structuredClone(artifact);
  }

  async updateArtifact(input: ArtifactUpdateInput): Promise<Artifact[]> {
    const artifacts = await this.ensureLoaded();
    const artifact = artifacts.find((candidate) => candidate.id === input.artifactId);
    if (!artifact) {
      throw new Error("Artifact was not found.");
    }

    const now = Date.now();
    const versionId = makeId("version");
    const nextArtifact: Artifact = {
      ...artifact,
      title: artifact.title,
      summary: input.summary || artifact.summary,
      activeVersionId: versionId,
      versions: [
        ...artifact.versions,
        {
          id: versionId,
          createdAt: now,
          prompt: input.prompt || "Manual edit",
          summary: input.summary || "Updated in Artifact Studio.",
          content: input.content.kind === artifact.kind ? input.content : defaultArtifactContent(artifact.kind)
        }
      ],
      updatedAt: now
    };

    this.artifacts = artifacts.map((candidate) => (candidate.id === artifact.id ? nextArtifact : candidate));
    await this.save();
    return structuredClone(this.artifacts);
  }

  async exportArtifact(artifactId: string): Promise<ArtifactExportResult> {
    const artifacts = await this.ensureLoaded();
    const artifact = artifacts.find((candidate) => candidate.id === artifactId);
    if (!artifact) {
      return {
        success: false,
        artifactId,
        reason: "Artifact was not found."
      };
    }

    try {
      const exportRoot = this.getExportRoot();
      await fs.mkdir(exportRoot, { recursive: true });
      const version = getActiveArtifactVersion(artifact);
      const baseName = sanitizeFileName(artifact.title);
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");

      if (version.content.kind === "document") {
        const exportPath = path.join(exportRoot, `${baseName}-${timestamp}.docx`);
        await fs.writeFile(exportPath, await createDocxBuffer(artifact.title, version.content.markdown));
        return { success: true, artifactId, kind: artifact.kind, path: exportPath, exportedAt: Date.now() };
      }

      if (version.content.kind === "slide_deck") {
        const exportPath = path.join(exportRoot, `${baseName}-${timestamp}.pptx`);
        await fs.writeFile(exportPath, await createPptxBuffer(artifact.title, version.content.slides));
        return { success: true, artifactId, kind: artifact.kind, path: exportPath, exportedAt: Date.now() };
      }

      const folderPath = path.join(exportRoot, `${baseName}-${timestamp}`);
      await fs.mkdir(folderPath, { recursive: true });
      await fs.writeFile(path.join(folderPath, "index.html"), createWebsiteHtml(artifact.title, version.content.html), "utf8");
      await fs.writeFile(path.join(folderPath, "styles.css"), version.content.css, "utf8");
      return { success: true, artifactId, kind: artifact.kind, path: folderPath, exportedAt: Date.now() };
    } catch (error) {
      return {
        success: false,
        artifactId,
        kind: artifact.kind,
        reason: error instanceof Error ? error.message : "Artifact export failed."
      };
    }
  }

  async exportArtifactToCoding(
    artifactId: string
  ): Promise<Omit<Extract<ArtifactExportToCodingResult, { success: true }>, "codingSnapshot"> | Extract<ArtifactExportToCodingResult, { success: false }>> {
    const artifacts = await this.ensureLoaded();
    const artifact = artifacts.find((candidate) => candidate.id === artifactId);
    if (!artifact) {
      return {
        success: false,
        artifactId,
        reason: "Artifact was not found."
      };
    }

    if (artifact.kind !== "website_design") {
      return {
        success: false,
        artifactId,
        kind: artifact.kind,
        reason: "Only website designs can be exported to the coding workspace."
      };
    }

    try {
      const version = getActiveArtifactVersion(artifact);
      if (version.content.kind !== "website_design") {
        return {
          success: false,
          artifactId,
          kind: artifact.kind,
          reason: "This artifact does not have website design content."
        };
      }

      const folderPath = await createUniqueFolder(path.join(path.dirname(this.getExportRoot()), "Autopilot Coding Projects"), sanitizeFileName(artifact.title));
      await fs.mkdir(folderPath, { recursive: true });
      await fs.writeFile(path.join(folderPath, "index.html"), createWebsiteHtml(artifact.title, version.content.html), "utf8");
      await fs.writeFile(path.join(folderPath, "styles.css"), version.content.css, "utf8");
      await fs.writeFile(
        path.join(folderPath, "README.md"),
        `# ${artifact.title}\n\nExported from Autopilot Design Studio.\n\nOpen \`index.html\` to preview the design.\n`,
        "utf8"
      );

      artifact.exportedProjectPath = folderPath;
      artifact.updatedAt = Date.now();
      await this.save();

      return {
        success: true,
        artifactId,
        kind: artifact.kind,
        path: folderPath,
        projectRootPath: folderPath,
        exportedAt: Date.now()
      };
    } catch (error) {
      return {
        success: false,
        artifactId,
        kind: artifact.kind,
        reason: error instanceof Error ? error.message : "Artifact export to coding failed."
      };
    }
  }

  private async ensureLoaded(): Promise<Artifact[]> {
    if (this.artifacts) {
      return this.artifacts;
    }

    try {
      const parsed = JSON.parse(await fs.readFile(this.getArtifactsPath(), "utf8")) as Partial<ArtifactFile>;
      this.artifacts = sanitizeArtifacts(parsed.artifacts);
    } catch (error) {
      const code = error && typeof error === "object" && "code" in error ? (error as NodeJS.ErrnoException).code : undefined;
      if (code !== "ENOENT") {
        console.warn("Autopilot could not load artifacts.", error);
      }
      this.artifacts = [];
    }

    return this.artifacts;
  }

  private async save(): Promise<void> {
    if (!this.artifacts) {
      return;
    }

    const artifactsPath = this.getArtifactsPath();
    await fs.mkdir(path.dirname(artifactsPath), { recursive: true });
    const payload: ArtifactFile = {
      version: 1,
      artifacts: this.artifacts
    };
    await fs.writeFile(artifactsPath, JSON.stringify(payload, null, 2), "utf8");
  }

  private getArtifactsPath(): string {
    const dataRoot = typeof this.dataRoot === "function" ? this.dataRoot() : this.dataRoot;
    return path.join(dataRoot, ARTIFACTS_FILE);
  }

  private getExportRoot(): string {
    return typeof this.exportRoot === "function" ? this.exportRoot() : this.exportRoot;
  }
}

function makeId(prefix: string): string {
  return `${prefix}:${randomUUID()}`;
}

function sanitizeFileName(value: string): string {
  const cleaned = value
    .trim()
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "-")
    .replace(/\s+/g, " ")
    .slice(0, 80);
  return cleaned || "Autopilot artifact";
}

async function createUniqueFolder(rootPath: string, baseName: string): Promise<string> {
  const safeBaseName = baseName || "Autopilot design";
  for (let index = 0; index < 100; index += 1) {
    const suffix = index === 0 ? "" : `-${index + 1}`;
    const candidate = path.join(rootPath, `${safeBaseName}${suffix}`);
    try {
      await fs.access(candidate);
    } catch {
      return candidate;
    }
  }

  return path.join(rootPath, `${safeBaseName}-${Date.now()}`);
}

function createWebsiteHtml(title: string, bodyHtml: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
${bodyHtml}
</body>
</html>`;
}

async function createDocxBuffer(title: string, markdown: string): Promise<Buffer> {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>`);
  zip.folder("_rels")?.file(".rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>`);
  zip.folder("docProps")?.file("core.xml", createCoreProperties(title));
  zip.folder("docProps")?.file("app.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>Autopilot</Application>
</Properties>`);
  zip.folder("word")?.file("styles.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:b/><w:sz w:val="40"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:pPr><w:outlineLvl w:val="1"/></w:pPr><w:rPr><w:b/><w:sz w:val="30"/></w:rPr></w:style>
</w:styles>`);
  zip.folder("word")?.file("document.xml", createDocumentXml(markdown));
  return zip.generateAsync({ type: "nodebuffer" });
}

function createDocumentXml(markdown: string): string {
  const paragraphs = markdown
    .replace(/\r/g, "")
    .split("\n")
    .flatMap((line) => {
      const trimmed = line.trim();
      if (!trimmed) {
        return ['<w:p/>'];
      }

      if (trimmed.startsWith("# ")) {
        return [createWordParagraph(trimmed.slice(2), "Heading1")];
      }

      if (trimmed.startsWith("## ")) {
        return [createWordParagraph(trimmed.slice(3), "Heading2")];
      }

      return [createWordParagraph(trimmed.replace(/^[-*]\s+/u, "• "))];
    })
    .join("");

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${paragraphs}
    <w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
  </w:body>
</w:document>`;
}

function createWordParagraph(text: string, style?: string): string {
  const styleXml = style ? `<w:pPr><w:pStyle w:val="${style}"/></w:pPr>` : "";
  return `<w:p>${styleXml}<w:r><w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r></w:p>`;
}

async function createPptxBuffer(title: string, slides: SlideArtifactSlide[]): Promise<Buffer> {
  const zip = new JSZip();
  const slideOverrides = slides
    .map(
      (_slide, index) =>
        `<Override PartName="/ppt/slides/slide${index + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`
    )
    .join("\n  ");
  zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  ${slideOverrides}
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>`);
  zip.folder("_rels")?.file(".rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>`);
  zip.folder("docProps")?.file("core.xml", createCoreProperties(title));
  zip.folder("docProps")?.file("app.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>Autopilot</Application>
  <Slides>${slides.length}</Slides>
</Properties>`);

  const rels = slides
    .map(
      (_slide, index) =>
        `<Relationship Id="rId${index + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${index + 1}.xml"/>`
    )
    .join("\n  ");
  const slideIds = slides.map((_slide, index) => `<p:sldId id="${256 + index}" r:id="rId${index + 1}"/>`).join("");
  zip.folder("ppt")?.file("presentation.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:sldIdLst>${slideIds}</p:sldIdLst>
  <p:sldSz cx="12192000" cy="6858000" type="wide"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>`);
  zip.folder("ppt")?.folder("_rels")?.file("presentation.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  ${rels}
</Relationships>`);

  const slidesFolder = zip.folder("ppt")?.folder("slides");
  slides.forEach((slide, index) => {
    slidesFolder?.file(`slide${index + 1}.xml`, createSlideXml(slide));
  });

  return zip.generateAsync({ type: "nodebuffer" });
}

function createSlideXml(slide: SlideArtifactSlide): string {
  const bulletRuns = slide.bullets
    .map(
      (bullet, index) => `<a:p>
        <a:pPr marL="342900" indent="-171450"><a:buChar char="•"/></a:pPr>
        <a:r><a:rPr lang="en-US" sz="${index === 0 ? 2600 : 2300}"/><a:t>${escapeXml(bullet)}</a:t></a:r>
      </a:p>`
    )
    .join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="650000" y="420000"/><a:ext cx="10800000" cy="1000000"/></a:xfrm></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="4300" b="1"/><a:t>${escapeXml(slide.title)}</a:t></a:r></a:p></p:txBody>
      </p:sp>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="Body"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="780000" y="1700000"/><a:ext cx="10400000" cy="4200000"/></a:xfrm></p:spPr>
        <p:txBody><a:bodyPr/><a:lstStyle/>${bulletRuns}</p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>`;
}

function createCoreProperties(title: string): string {
  const now = new Date().toISOString();
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>${escapeXml(title)}</dc:title>
  <dc:creator>Autopilot</dc:creator>
  <cp:lastModifiedBy>Autopilot</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">${now}</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">${now}</dcterms:modified>
</cp:coreProperties>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => {
    switch (character) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      case "'":
        return "&#39;";
      default:
        return character;
    }
  });
}

function escapeXml(value: string): string {
  return escapeHtml(value);
}
